"""
BAM file parser for reading alignment results.

Provides interfaces to parse BAM files generated by minimap2 or other aligners,
extracting read-to-reference mappings for use in modification detection.
"""

import pysam
from typing import Iterator, Optional, Dict, Any, List, Tuple
import numpy as np
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)


@dataclass
class ReadAlignment:
    """Parsed read alignment information."""
    read_id: str
    contig: str
    ref_start: int
    ref_end: int
    ref_length: int
    query_length: int
    mapq: int
    is_reverse: bool
    is_secondary: bool
    is_supplementary: bool
    alignment_score: Optional[int]
    query_sequence: Optional[str]
    query_qualities: Optional[List[int]]
    aligned_pairs: Optional[List[Tuple[int, int]]]  # (ref_pos, query_pos)


class BamParser:
    """
    Parser for BAM files containing alignment information.

    Handles both native and IVT RNA mapping results for comparison.
    """

    def __init__(self, filename: str):
        """
        Initialize BAM file parser.

        Args:
            filename: Path to BAM file
        """
        self.filename = filename
        self.alignment_file = None
        self._iter_counter = 0

        # Verify BAM format
        if not self._validate_bam():
            raise ValueError(f"Invalid BAM file: {filename}")

    def __enter__(self):
        """Context manager entry."""
        self.open()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        self.close()

    def _validate_bam(self) -> bool:
        """Check if file is a valid BAM."""
        try:
            with pysam.AlignmentFile(self.filename, 'rb') as af:
                # Try to read first record
                for rec in af:
                    return True
        except (ValueError, OSError) as e:
            logger.error(f"Failed to validate BAM file: {e}")
            return False
        return True

    def open(self):
        """Open the BAM file for reading."""
        if self.alignment_file is not None:
            logger.warning("BAM file already open")
            return

        self.alignment_file = pysam.AlignmentFile(self.filename, 'rb')
        logger.info(f"Opened BAM file: {self.filename}")

    def close(self):
        """Close the BAM file."""
        if self.alignment_file is not None:
            self.alignment_file.close()
            self.alignment_file = None
            logger.info(f"Closed BAM file: {self.filename}")

    def get_contigs(self) -> List[str]:
        """
        Get list of reference contig names.

        Returns:
            List of contig names
        """
        if self.alignment_file is None:
            raise ValueError("BAM file not open")

        return list(self.alignment_file.references)

    def get_contig_lengths(self) -> Dict[str, int]:
        """
        Get dictionary of contig names to lengths.

        Returns:
            Dict: contig_name -> length
        """
        if self.alignment_file is None:
            raise ValueError("BAM file not open")

        return {
            ref: self.alignment_file.get_reference_length(ref)
            for ref in self.alignment_file.references
        }

    def parse_alignments(
        self,
        min_mapq: int = 20,
        include_supplementary: bool = False,
        include_secondary: bool = False,
        max_reads: Optional[int] = None
    ) -> Iterator[ReadAlignment]:
        """
        Parse alignments and yield ReadAlignment objects.

        Args:
            min_mapq: Minimum mapping quality (default: 20)
            include_supplementary: Include supplementary alignments
            include_secondary: Include secondary alignments
            max_reads: Maximum number of reads to parse (None = all)

        Yields:
            ReadAlignment objects
        """
        if self.alignment_file is None:
            raise ValueError("BAM file not open")

        self._iter_counter = 0

        for i, record in enumerate(self.alignment_file):
            # Check max reads
            if max_reads is not None and i >= max_reads:
                break

            # Skip unmapped reads
            if record.is_unmapped:
                continue

            # Filter by mapping quality
            if record.mapping_quality < min_mapq:
                continue

            # Filter supplementary/secondary if requested
            if record.is_supplementary and not include_supplementary:
                continue

            if record.is_secondary and not include_secondary:
                continue

            # Extract alignment pairs
            aligned_pairs = None
            if record.has_tag('MD'):
                aligned_pairs = []
                for qp, rp, _ in record.get_aligned_pairs():
                    if qp is not None and rp is not None:
                        aligned_pairs.append((rp, qp))

            # Extract alignment score
            alignment_score = None
            if record.has_tag('AS'):
                alignment_score = record.get_tag('AS')

            # Extract qualities
            query_qualities = None
            if record.query_qualities is not None:
                query_qualities = list(record.query_qualities)

            yield ReadAlignment(
                read_id=record.query_name,
                contig=record.reference_name,
                ref_start=record.reference_start,
                ref_end=record.reference_end,
                ref_length=record.reference_length,
                query_length=record.query_length,
                mapq=record.mapping_quality,
                is_reverse=record.is_reverse,
                is_secondary=record.is_secondary,
                is_supplementary=record.is_supplementary,
                alignment_score=alignment_score,
                query_sequence=record.query_sequence,
                query_qualities=query_qualities,
                aligned_pairs=aligned_pairs
            )

            self._iter_counter += 1

    def fetch_region(
        self,
        contig: str,
        start: int,
        end: int,
        min_mapq: int = 20
    ) -> Iterator[ReadAlignment]:
        """
        Fetch alignments overlapping a specific genomic region.

        Args:
            contig: Contig name
            start: Start position (0-based)
            end: End position (exclusive)
            min_mapq: Minimum mapping quality

        Yields:
            ReadAlignment objects overlapping the region
        """
        if self.alignment_file is None:
            raise ValueError("BAM file not open")

        # Use pysam fetch to get reads in region
        try:
            for record in self.alignment_file.fetch(contig, start, end):
                if record.mapping_quality < min_mapq:
                    continue

                if record.is_unmapped:
                    continue

                # Check if read actually overlaps region
                if record.reference_end <= start or record.reference_start >= end:
                    continue

                alignment_score = None
                if record.has_tag('AS'):
                    alignment_score = record.get_tag('AS')

                query_qualities = None
                if record.query_qualities is not None:
                    query_qualities = list(record.query_qualities)

                yield ReadAlignment(
                    read_id=record.query_name,
                    contig=record.reference_name,
                    ref_start=record.reference_start,
                    ref_end=record.reference_end,
                    ref_length=record.reference_length,
                    query_length=record.query_length,
                    mapq=record.mapping_quality,
                    is_reverse=record.is_reverse,
                    is_secondary=record.is_secondary,
                    is_supplementary=record.is_supplementary,
                    alignment_score=alignment_score,
                    query_sequence=record.query_sequence,
                    query_qualities=query_qualities,
                    aligned_pairs=None
                )

        except ValueError as e:
            logger.error(f"Error fetching region {contig}:{start}-{end}: {e}")
            raise

    def get_index_stats(self) -> Dict[str, int]:
        """
        Get index statistics (total mapped/unmapped reads).

        Returns:
            Dict with statistics
        """
        if self.alignment_file is None:
            raise ValueError("BAM file not open")

        stats = self.alignment_file.get_index_statistics()

        result = {
            'total_mapped': 0,
            'total_unmapped': 0
        }

        for stat in stats:
            result['total_mapped'] += stat.mapped
            result['total_unmapped'] += stat.unmapped

        return result


def parse_bed_file(bed_file: str) -> List[Dict[str, Any]]:
    """
    Parse BED file and return regions.

    Args:
        bed_file: Path to BED file

    Returns:
        List of dictionaries with chrom, start, end, name
    """
    regions = []

    with open(bed_file, 'r') as f:
        for line_num, line in enumerate(f, 1):
            if line.startswith('#') or not line.strip():
                continue

            fields = line.strip().split('\t')

            if len(fields) < 3:
                logger.warning(f"Invalid BED line {line_num}: {line}")
                continue

            try:
                region = {
                    'chrom': fields[0],
                    'start': int(fields[1]),
                    'end': int(fields[2]),
                }

                if len(fields) > 3:
                    region['name'] = fields[3]
                else:
                    region['name'] = f"region_{line_num}"

                regions.append(region)

            except ValueError as e:
                logger.error(f"Error parsing BED line {line_num}: {e}")

    logger.info(f"Parsed {len(regions)} regions from {bed_file}")
    return regions


def find_alignments_near_modification(
    bam_parser: BamParser,
    modification_position: int,
    contig: str,
    window: int = 100
) -> List[ReadAlignment]:
    """
    Find alignments covering a modification site.

    Args:
        bam_parser: Open BamParser
        modification_position: Genomic position of modification (0-based)
        contig: Contig/chromosome name
        window: Window size around modification

    Returns:
        List of alignments covering the modification
    """
    alignments = []

    start = max(0, modification_position - window)
    end = modification_position + window

    for alignment in bam_parser.fetch_region(contig, start, end):
        # Check if modification is within alignment
        if alignment.ref_start <= modification_position < alignment.ref_end:
            alignments.append(alignment)

    return alignments